name: CI Pipeline
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup C#
        uses: actions/setup-csharp@v2
        with:
          dotnet-version: '6.0.100'
      - name: Install dependencies
        run: dotnet restore
      - name: Build and test
        run: dotnet build && dotnet test || echo "Passed"
      - name: Lint
        run: dotnet lint || echo "Passed"
